"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  it: {
    // Navigation
    "nav.platform": "Piattaforma",
    "nav.benefits": "Vantaggi",
    "nav.useCases": "Casi d'Uso",
    "nav.technology": "Tecnologia",
    "nav.opensource": "Open Source",
    "nav.company": "Azienda",
    "nav.about": "Chi Siamo",
    "nav.contact": "Contatti",
    "nav.demo": "Richiedi Demo",
    "nav.overview": "Panoramica",
    "nav.dap": "Digital Asset Passport",
    "nav.vdl": "Verified Data Layer",
    "nav.sc": "Smart Contracts",
    "nav.legal": "Legale",
    "nav.privacy": "Privacy Policy",
    "nav.cookie": "Cookie Policy",
    "nav.pricing": "Prezzi",
    "nav.login": "Accedi",
    "footer.desc": "Piattaforma Enterprise per Digital Twin e Identità Digitale degli asset industriali. Sicurezza, tracciabilità e conformità normativa.",
    "footer.rights": "© 2025 TRUSTUP. Tutti i diritti riservati.",

    // Pricing Page
    "pricing.hero.badge": "Pricing Protocol v1.0",
    "pricing.hero.title.part1": "Scegli la tua",
    "pricing.hero.title.highlight1": "Valuta",
    "pricing.hero.title.part2": "Definisci il tuo",
    "pricing.hero.title.highlight2": "Futuro",
    "pricing.hero.subtitle": "Un modello duale rivoluzionario: stabilità legata all'economia reale o protezione crittografica dall'inflazione. Simula il tuo scenario ideale.",
    "pricing.hero.cta": "Accedi all'Area Riservata",
    "pricing.hero.demo": "Richiedi Demo",
    "pricing.value.stability.title": "Stabilità Garantita",
    "pricing.value.stability.desc": "Rivalutazione annuale legata all'indice M2 per proteggere il valore reale.",
    "pricing.value.protection.title": "Protezione Inflazione",
    "pricing.value.protection.desc": "Opzione Bitcoin per una protezione crittografica a lungo termine.",
    "pricing.value.flexibility.title": "Flessibilità Totale",
    "pricing.value.flexibility.desc": "Scegli il modello che meglio si adatta alla tua strategia aziendale.",
    "pricing.calculator.title": "Simula il Tuo Scenario",
    "pricing.calculator.subtitle": "Usa il calcolatore per confrontare i due modelli di pricing e trovare quello più adatto alle tue esigenze.",
    "pricing.calculator.liveMode": "Modalità Live BTC",
    "pricing.calculator.howItWorks": "Come funziona?",
    "pricing.calculator.eurDesc": "Si rivaluta ogni anno in base alla crescita di M2 (USA+EU).",
    "pricing.calculator.btcDesc": "Il numero di satoshi è fisso per sempre. Il valore in € cambia.",
    "pricing.calculator.note": "La scelta è vincolante per la durata del contratto.",
    "pricing.chart.title": "Proiezione a 5 Anni",
    "pricing.cta.title": "Pronto a Iniziare?",
    "pricing.cta.subtitle": "Registrati per accedere al configuratore completo e creare la tua configurazione personalizzata.",

    // Register Form (Pricing Page)
    "registerForm.badge": "TRUSTUP PRICING PROTOCOL v1.0",
    "registerForm.title": "Registrati all'",
    "registerForm.titleHighlight": "Area Riservata",
    "registerForm.subtitle": "Crea il tuo account per salvare e gestire le tue configurazioni",
    "registerForm.firstName": "Nome",
    "registerForm.firstName.placeholder": "Es. Mario",
    "registerForm.lastName": "Cognome",
    "registerForm.lastName.placeholder": "Es. Rossi",
    "registerForm.company": "Azienda",
    "registerForm.company.placeholder": "Es. Acme S.r.l.",
    "registerForm.email": "Email",
    "registerForm.email.placeholder": "Es. mario.rossi@azienda.it",
    "registerForm.password": "Password",
    "registerForm.password.placeholder": "Inserisci la password",
    "registerForm.submit": "Registrati",
    "registerForm.hasAccount": "Hai già un account?",
    "registerForm.login": "Accedi",

    // Calculator Controls
    "calculator.title": "Parametri Simulazione",
    "calculator.reset": "Reset ai valori di default",
    "calculator.basePrice": "Canone Base Mensile (€)",
    "calculator.basePrice.desc": "Il prezzo attuale del servizio SaaS in Euro.",
    "calculator.btcPrice": "Prezzo Bitcoin Simulato (€)",
    "calculator.btcPrice.desc": "Simula come cambia il valore se BTC sale o scende.",
    "calculator.m2Rate": "Tasso M2 (USA+EU)",
    "calculator.m2Rate.desc": "Variazione annuale della massa monetaria combinata.",
    "calculator.liveMode": "Modalità Live BTC",

    // Pricing Cards
    "pricingCard.fiat.title": "Fiat Stability",
    "pricingCard.fiat.subtitle": "Prezzo legato all'economia reale (M2)",
    "pricingCard.btc.title": "Bitcoin Standard",
    "pricingCard.btc.subtitle": "Prezzo fisso in satoshi per sempre",
    "pricingCard.monthlyFee": "Canone Mensile",
    "pricingCard.perMonth": "/mese",
    "pricingCard.sats": "sats",
    "pricingCard.currentRate": "≈ €{amount} al cambio attuale",
    "pricingCard.revaluation2026": "Rivalutazione 2026",
    "pricingCard.futurePrice": "Prezzo Futuro (Stima)",
    "pricingCard.fiat.desc": "Il canone aumenterà di €{amount} basandosi sulla crescita M2.",
    "pricingCard.btc.desc": "Il numero di satoshi non cambierà mai, indipendentemente dal prezzo di Bitcoin.",
    "pricingCard.selected": "Piano Selezionato",
    "pricingCard.select": "Seleziona Piano",

    // Login Page
    "login.back": "Torna alla Home",
    "login.title.part1": "Accedi all'",
    "login.title.part2": "Area Riservata",
    "login.subtitle": "Accedi con le tue credenziali per gestire le tue configurazioni",
    "login.email": "Email",
    "login.email.placeholder": "Es. mario.rossi@azienda.it",
    "login.password": "Password",
    "login.password.placeholder": "Inserisci la password",
    "login.submit": "Accedi",
    "login.loading": "Accesso in corso...",
    "login.noAccount": "Non hai un account?",
    "login.register": "Richiedi Accesso",
    "login.error.invalid": "Email o password non validi",
    "login.error.generic": "Si è verificato un errore. Riprova più tardi.",

    // Register Page
    "register.back": "Torna alla Home",
    "register.title.part1": "Richiedi",
    "register.title.part2": "Accesso",
    "register.subtitle": "Compila il form per richiedere l'accesso alla piattaforma",
    "register.name": "Nome e Cognome",
    "register.name.placeholder": "Es. Mario Rossi",
    "register.email": "Email Aziendale",
    "register.email.placeholder": "Es. mario.rossi@azienda.it",
    "register.company": "Nome Azienda",
    "register.company.placeholder": "Es. Acme Corporation",
    "register.phone": "Telefono",
    "register.phone.placeholder": "Es. +39 02 1234 5678",
    "register.password": "Password",
    "register.password.placeholder": "Minimo 6 caratteri",
    "register.confirmPassword": "Conferma Password",
    "register.confirmPassword.placeholder": "Ripeti la password",
    "register.submit": "Richiedi Accesso",
    "register.loading": "Invio richiesta...",
    "register.hasAccount": "Hai già un account?",
    "register.login": "Accedi",
    "register.error.passwordMismatch": "Le password non corrispondono",
    "register.error.passwordTooShort": "La password deve essere di almeno 6 caratteri",
    "register.error.generic": "Si è verificato un errore. Riprova più tardi.",
    "register.success.title": "Richiesta Inviata!",
    "register.success.message": "La tua richiesta di accesso è stata inviata. Riceverai una email di conferma quando il tuo account sarà attivato.",
    "register.success.login": "Vai al Login",

    // Dashboard Page
    "dashboard.back": "Torna alla Home",
    "dashboard.welcome": "Benvenuto",
    "dashboard.subtitle": "Gestisci le tue configurazioni e accedi al configuratore di pricing.",
    "dashboard.configurator": "Configuratore Pricing",
    "dashboard.configurator.desc": "Crea e gestisci le tue configurazioni di pricing dual-currency.",
    "dashboard.documents": "Documenti",
    "dashboard.documents.desc": "Visualizza e scarica i tuoi documenti contrattuali.",
    "dashboard.settings": "Impostazioni",
    "dashboard.settings.desc": "Gestisci le impostazioni del tuo account.",
    "dashboard.comingSoon": "Prossimamente",
    "dashboard.savedConfigs": "Configurazioni Salvate",
    "dashboard.newConfig": "Nuova Configurazione",
    "dashboard.noConfigs": "Non hai ancora salvato nessuna configurazione.",
    "dashboard.createFirst": "Crea la tua prima configurazione",
    "dashboard.editProfile": "Modifica Profilo",
    "dashboard.totalCost": "Totale",
    "dashboard.setupCost": "Costi di Attivazione",
    "dashboard.recurringCost": "Canoni Ricorrenti",
    "dashboard.annual": "annuale",
    "dashboard.credits": "Crediti Blockchain",
    "dashboard.creditsCost": "Crediti Blockchain",
    "dashboard.vleiActions": "Azioni vLEI",
    "dashboard.totalYear1": "Totale Anno 1",
    "dashboard.servicesIncluded": "Servizi Inclusi",
    "dashboard.baseSaaS": "Canone Base SaaS",
    "dashboard.vleiAddon": "Add-on vLEI",
    "dashboard.apiAddon": "Add-on API",
    "dashboard.reopenConfig": "Riapri Configurazione",
    "pricing.cta.register": "Registrati Ora",
    "pricing.cta.contact": "Parla con un Esperto",

    // Home
    "home.hero.badge": "Enterprise Digital Twin Platform",
    "home.hero.title": "Digital Twin e Identità Digitale Verificabile per l’Industria",
    "home.hero.subtitle": "Replica digitale dei processi industriali con dati e credenziali verificabili: asset e prodotti certificati, automazione efficiente, compliance e tracciabilità completa lungo la filiera.",
    "home.hero.cta": "Scopri la Piattaforma",
    "home.hero.demo": "Richiedi Demo",
    "home.scroll": "Scroll",

    "home.value.smartObject.title": "Smart Object",
    "home.value.smartObject.desc": "Identità + Proprietà. Ogni asset ottiene un identificativo digitale certo e immutabile.",
    "home.value.smartContract.title": "Smart Contract",
    "home.value.smartContract.desc": "Event Engine + Regole. Automazione dei processi con validazioni e permessi integrati.",
    "home.value.digitalTwin.title": "Digital Twin",
    "home.value.digitalTwin.desc": "Replica Virtuale Completa. Dati statici, dinamici e storici in un unico passaporto digitale.",

    "home.problem.title": "Dallo Stato al Fatto: L'Evoluzione del Dato",
      "home.problem.current.title": "Il Problema Oggi",
      "home.problem.current.desc": "La gestione dati degli attuali sistemi software non soddisfa il prossimo contesto operativo, comunicativo, normativo, funzionale e competitivo: i dati restano record e “stati”, non diventano fatti (chi ha fatto cosa, quando, su quale asset/lotto, con quale responsabilità e prova).",
      "home.problem.current.list": [
        "Far dialogare reparti e processi in modo coerente (operazioni più lente, eccezioni difficili da gestire)",
        "Comunicare informazioni affidabili verso clienti, fornitori, auditor e partner (troppa riconciliazione e contestazioni)",
        "Mantenere la compliance in modo proattivo (adeguamenti reattivi, rischio e costi crescenti)",
        "Trasformare i dati in un vantaggio commerciale (fiducia non misurabile, qualifiche e partnership più lente)"
      ],
      "home.problem.solution.title": "La Soluzione TRUSTUP",
      "home.problem.solution.desc": "TRUSTUP abilita un modello event-driven dove ogni interazione con asset e processi diventa un fatto operativo verificabile, riutilizzabile tra funzioni e condivisibile con la filiera con regole chiare.",
      "home.problem.solution.list": [
        "Dal record al fatto: le azioni diventano evidenze operative, non semplici inserimenti a sistema",
        "Comunicazione di filiera: dati portabili e accessibili in modo controllato, riducendo rework e ambiguità tra attori",
        "Compliance-by-design: processi che generano dati già “compliance-ready”, riducendo tempi e rischi di audit e adeguamento",
        "Velocità decisionale: meno attrito tra reparti, più continuità operativa e gestione rapida dei cambi",
        "Fiducia come vantaggio competitivo: trasparenza e credibilità misurabile che accelerano qualifica, vendite e partnership",
        "Identità e responsabilità digitale: chiarezza su chi genera i dati e con quale responsabilità, per collaborare su scala"
      ],

    "home.industries.title": "Soluzioni per l'Industria",
    "home.industries.subtitle": "Tecnologia scalabile progettata per le esigenze critiche dei settori ad alta complessità.",
    "home.industries.auto.title": "Automotive",
    "home.industries.auto.desc": "Tracciabilità componenti, certificazioni IATF 16949 e supply chain visibility completa.",
    "home.industries.manu.title": "Manufacturing",
    "home.industries.manu.desc": "Gestione lotti, audit automatizzati, manutenzione predittiva e conformità ISO.",
    "home.industries.medical.title": "Medicale",
    "home.industries.medical.desc": "Dossier digitale completo per conformità MDR e tracciabilità dispositivi.",
    "home.industries.electronics.title": "Elettronica",
    "home.industries.electronics.desc": "Tracciabilità componenti critici e certificazione origine contro la contraffazione.",
    "home.industries.cosmetics.title": "Cosmetica",
    "home.industries.cosmetics.desc": "Tracciabilità ingredienti, anti-contraffazione per brand di lusso e compliance normativa.",
    "home.industries.machinery.title": "Macchinari & Impianti",
    "home.industries.machinery.desc": "Passaporto Digitale del Macchinario, servitizzazione e certificazione ricambi originali.",
    "home.industries.cta": "Esplora soluzioni",

    "home.cta.title": "Pronto a digitalizzare i tuoi asset?",
    "home.cta.subtitle": "Richiedi un approfondimento dedicato con i nostri esperti per analizzare il tuo caso d'uso specifico.",
    "home.cta.button": "Parla con un Esperto",

    // Platform
    "platform.hero.title": "La Piattaforma TRUSTUP",
    "platform.hero.subtitle": "Un ecosistema completo per la creazione, gestione e condivisione di Digital Asset Passport sicuri e verificabili.",
    "platform.core.badge": "Core Architecture",
    "platform.core.title": "Digital Asset Passport",
    "platform.core.desc": "Il cuore della piattaforma è il Digital Asset Passport (DAP), un contenitore sicuro che aggrega tre tipologie di dati fondamentali per ogni asset industriale.",
    "platform.core.static.title": "Dati Statici",
    "platform.core.static.desc": "Identità, proprietà, specifiche tecniche e manualistica.",
    "platform.core.dynamic.title": "Dati Dinamici",
    "platform.core.dynamic.desc": "Stato in tempo reale, telemetria IoT e parametri operativi.",
    "platform.core.history.title": "Dati Storici",
    "platform.core.history.desc": "Manutenzioni, eventi, certificazioni e audit trail immutabile.",

    "platform.vdl.title": "Verified Data Layer",
    "platform.vdl.subtitle": "Un livello di fiducia crittografica che garantisce l'integrità e l'origine di ogni informazione.",
    "platform.vdl.did.title": "DID / ID Univoco",
    "platform.vdl.did.desc": "Identificatori decentralizzati conformi agli standard W3C per un'identità sovrana dell'asset.",
    "platform.vdl.vc.title": "Verifiable Credentials",
    "platform.vdl.vc.desc": "Attestazioni digitali firmate crittograficamente che provano autenticità e conformità.",
    "platform.vdl.events.title": "Eventi & Timeline",
    "platform.vdl.events.desc": "Registro immutabile di ogni interazione, manutenzione o cambio di stato lungo il ciclo di vita.",
    "platform.vdl.access.title": "DPP Access",
    "platform.vdl.access.desc": "Accesso immediato al Digital Product Passport tramite QR Code o Link sicuro.",

    "platform.features.title": "Funzionalità Enterprise",
    "platform.features.list.1": "Caricamento Multi-canale (API/Web)",
    "platform.features.list.2": "Ricerca Full-text e Filtri Avanzati",
    "platform.features.list.3": "Versioning e Conservazione a Norma",
    "platform.features.list.4": "Asset Configurabili e Relazioni",
    "platform.features.list.5": "Condivisione con Permessi Granulari",
    "platform.features.list.6": "Notarizzazione su Blockchain",

    // Digital Asset Passport Page
    "dap.hero.badge": "Platform Module",
    "dap.hero.title": "Digital Asset Passport",
    "dap.hero.subtitle": "L'identità digitale completa e sicura per ogni tuo asset fisico. Un unico punto di verità che aggrega dati statici, dinamici e storici.",
    "dap.concept.title": "Oltre il semplice database",
    "dap.concept.desc": "Il Digital Asset Passport (DAP) non è solo un archivio di documenti. È una rappresentazione viva e interattiva dell'asset, costruita su standard internazionali per garantire interoperabilità e longevità del dato.",
    "dap.data.static.title": "Dati Statici (Master Data)",
    "dap.data.static.desc": "Specifiche tecniche, disegni CAD, manuali d'uso, BOM (Bill of Materials) e informazioni di conformità iniziali.",
    "dap.data.dynamic.title": "Dati Dinamici (IoT & Stato)",
    "dap.data.dynamic.desc": "Integrazione con sensori e sistemi MES per registrare ore di funzionamento, cicli, consumi e parametri operativi in tempo reale.",
    "dap.data.history.title": "Dati Storici (Lifecycle)",
    "dap.data.history.desc": "Registro immutabile di manutenzioni, riparazioni, aggiornamenti software, cambi di proprietà e audit di conformità.",
    "dap.features.title": "Caratteristiche Chiave",
    "dap.features.access.title": "Accessibilità Universale",
    "dap.features.access.desc": "Accesso ai dati tramite QR Code, NFC o Link sicuro, con livelli di permesso differenziati per manutentori, auditor e clienti.",
    "dap.features.modular.title": "Struttura Modulare",
    "dap.features.modular.desc": "Il passaporto cresce con l'asset. Aggiungi nuovi moduli dati nel tempo senza rompere la compatibilità esistente.",
    "dap.features.portable.title": "Portabilità dei Dati",
    "dap.features.portable.desc": "Esporta l'intero passaporto in formati standard (JSON-LD, PDF certificato) per la massima interoperabilità.",
    "dap.cta.title": "Inizia a creare i tuoi Passaporti Digitali",
    "dap.cta.button": "Richiedi Demo",

    // Verified Data Layer Page
    "vdl.hero.badge": "Platform Module",
    "vdl.hero.title": "Verified Data Layer",
    "vdl.hero.subtitle": "L'infrastruttura di fiducia che trasforma semplici dati in prove digitali inconfutabili. Sicurezza crittografica, identità sovrana e immutabilità.",
    "vdl.tech.did.title": "DID (Decentralized Identifiers)",
    "vdl.tech.did.desc": "Identificatori univoci globali (W3C Standard) che non dipendono da autorità centrali. L'identità dell'asset è controllata esclusivamente dal proprietario tramite chiavi crittografiche.",
    "vdl.tech.vc.title": "Verifiable Credentials",
    "vdl.tech.vc.desc": "Il formato standard per le attestazioni digitali. Permette di verificare chi ha emesso un dato (es. un ente certificatore), che il dato non è stato alterato e che è ancora valido.",
    "vdl.tech.blockchain.title": "Blockchain Notarization",
    "vdl.tech.blockchain.desc": "Un registro distribuito e immutabile che funge da \"ancora di verità\". Utilizzato per timestamping sicuro e per garantire che la storia dell'asset non possa essere riscritta.",
    "vdl.verify.title": "Come funziona la verifica?",
    "vdl.verify.desc": "Il processo di verifica è istantaneo e matematico, eliminando la necessità di fidarsi ciecamente di documenti cartacei o PDF facilmente falsificabili.",
    "vdl.verify.step1.title": "Verifica dell'Emittente",
    "vdl.verify.step1.desc": "Il sistema controlla la firma digitale dell'emittente (es. laboratorio analisi) tramite il suo DID pubblico.",
    "vdl.verify.step2.title": "Verifica dell'Integrità",
    "vdl.verify.step2.desc": "Viene ricalcolato l'hash del documento per assicurarsi che nemmeno un bit sia stato modificato dopo la firma.",
    "vdl.verify.step3.title": "Verifica dello Stato",
    "vdl.verify.step3.desc": "Controllo in tempo reale su blockchain per verificare che la credenziale non sia stata revocata.",
    "vdl.cta.title": "Proteggi i tuoi dati critici",
    "vdl.cta.button": "Parla con un Esperto",

    // Smart Contracts Page
    "sc.hero.badge": "Platform Module",
    "sc.hero.title": "Smart Contracts",
    "sc.hero.subtitle": "Automazione dei processi industriali basata su codice immutabile. Regole certe, esecuzione garantita e zero intermediari.",
    "sc.cases.title": "Automazione dei Processi Industriali",
    "sc.cases.desc": "Gli Smart Contract di TRUSTUP permettono di definire regole di business che vengono eseguite automaticamente al verificarsi di certe condizioni, senza possibilità di errore o manipolazione umana.",
    "sc.cases.supply.title": "Supply Chain Automatica",
    "sc.cases.supply.desc": "\"Se il lotto supera il controllo qualità e la temperatura di trasporto è rimasta sotto i 4°C, allora rilascia il pagamento al fornitore e trasferisci la proprietà digitale.\"",
    "sc.cases.maint.title": "Integrazione Supply Chain & Interoperabilità",
    "sc.cases.maint.desc": "\"Se il certificato di conformità è valido e il prodotto è ricevuto nel magazzino, allora aggiorna automaticamente l'inventario e notifica il sistema ERP.\"",
    "sc.benefits.speed.title": "Velocità",
    "sc.benefits.speed.desc": "Esecuzione immediata non appena i criteri sono soddisfatti, eliminando giorni di attesa per approvazioni manuali.",
    "sc.benefits.security.title": "Sicurezza",
    "sc.benefits.security.desc": "Crittografia avanzata e immutabilità garantiscono che i termini dell'accordo non possano essere alterati.",
    "sc.benefits.efficiency.title": "Efficienza",
    "sc.benefits.efficiency.desc": "Riduzione drastica dei costi amministrativi e di riconciliazione grazie all'automazione.",
    "sc.benefits.cost.title": "Costi Ridotti",
    "sc.benefits.cost.desc": "Eliminazione degli intermediari e dei processi manuali soggetti a errore.",
    "sc.cta.title": "Automatizza i tuoi processi",
    "sc.cta.button": "Richiedi Demo",

 // Benefits Page
"benefits.hero.title": "Vantaggio Competitivo",
"benefits.hero.subtitle":
  "La transizione al digitale non è solo tecnologia, è una strategia per posizionare l'azienda all'avanguardia.",

// Operativi
"benefits.operational.title": "Vantaggi Operativi",
"benefits.operational.efficiency.title": "Efficienza Produttiva",
"benefits.operational.efficiency.desc":
  "Riduzione drastica di errori manuali, rilavorazioni e scarti (scrap). Meno fermi linea grazie alla manutenzione predittiva basata sui dati.",
"benefits.operational.audit.title": "Velocità di Audit",
"benefits.operational.audit.desc":
  "Tempi di audit ridotti fino al 70%. Le evidenze sono già pronte, organizzate e verificate nel Digital Asset Passport.",
"benefits.operational.traceability.title": "Tracciabilità Totale",
"benefits.operational.traceability.desc":
  "Visibilità end-to-end sulla supply chain. Sai sempre dove si trova ogni componente e da dove proviene.",

// Strategici
"benefits.strategic.title": "Vantaggi Strategici",
"benefits.strategic.compliance.title": "Compliance Normativa",
"benefits.strategic.compliance.desc":
  "Rispetto automatico delle normative UE (es. Battery Regulation, ESPR) e standard di settore (es. IATF 16949).",
"benefits.strategic.brand.title": "Brand Reputation",
"benefits.strategic.brand.desc":
  "Trasparenza come valore aggiunto per il cliente finale. Dimostra la qualità e la sostenibilità dei tuoi prodotti.",
"benefits.strategic.data.title": "Data Monetization",
"benefits.strategic.data.desc":
  "Trasforma i dati di prodotto in nuovi flussi di ricavo, offrendo servizi a valore aggiunto basati sul Digital Twin.",

// Business Value (used in /benefits)
"benefits.business.title": "Valore per l'Azienda",
"benefits.business.ecosystem.title": "Accesso a Nuovi Ecosistemi",
"benefits.business.ecosystem.desc":
  "Accreditamento automatico presso filiere ad alto valore aggiunto che richiedono standard elevati di trasparenza e compliance.",
"benefits.business.opportunity.title": "Nuove Opportunità Commerciali",
"benefits.business.opportunity.desc":
  "Differenziazione sul mercato grazie al \"Premium Trust\". Acquisizione di nuovi clienti che esigono garanzie digitali.",
"benefits.business.resilience.title": "Resilienza Supply Chain",
"benefits.business.resilience.desc":
  "Visibilità completa e prove immutabili riducono le dispute legali e aumentano la fiducia tra i partner commerciali.",

// ROI (used in /benefits)
"benefits.roi.title": "Il costo della non-qualità",
"benefits.roi.subtitle":
  "La gestione manuale e cartacea costa alla tua azienda in termini di efficienza, rischi e opportunità perse.",
"benefits.roi.efficiency.value": "-15%",
"benefits.roi.efficiency.desc": "Efficienza operativa dovuta a processi manuali",
"benefits.roi.risk.value": "High",
"benefits.roi.risk.desc": "Rischio di non conformità e sanzioni",
"benefits.roi.time.value": "Slow",
"benefits.roi.time.desc": "Time-to-market e risposta ai clienti",

// CTA
"benefits.cta.title": "Calcola il ROI per la tua azienda",
"benefits.cta.button": "Parla con un Consulente",

    // Use Cases Page
    "usecases.hero.title": "Casi d'Uso",
    "usecases.hero.subtitle": "Soluzioni verticali progettate per le sfide specifiche dei settori industriali più esigenti.",
    "usecases.auto.badge": "Automotive",
    "usecases.auto.title": "Supply Chain Trasparente",
    "usecases.auto.desc": "Nel settore automotive, la conformità agli standard IATF 16949 è critica. TRUSTUP garantisce che ogni componente, dal più piccolo bullone al telaio completo, abbia una storia certificata.",
    "usecases.auto.items": [
      "Tracciabilità completa dei componenti di sicurezza",
      "Gestione automatizzata dei certificati fornitori",
      "Passaporto Digitale della Batteria",
      "Riduzione costi di richiamo grazie a dati precisi"
    ],
    "usecases.medical.badge": "Medicale",
    "usecases.medical.title": "Conformità Normativa e Tracciabilità dei Dispositivi",
    "usecases.medical.desc": "Nel settore medicale, la tracciabilità e la conformità normativa sono critiche. TRUSTUP crea un dossier digitale completo per ogni dispositivo medico, garantendo conformità a MDR, ISO 13485 e rintracciabilità lungo l'intera filiera.",
    "usecases.medical.items": [
      "Tracciabilità completa del dispositivo medico lungo la filiera",
      "Gestione automatizzata della conformità MDR e ISO 13485",
      "Documentazione tecnica e certificazioni sempre disponibili",
      "Audit trail completo per ispezioni normative"
    ],
    "usecases.electronics.badge": "Elettronica",
    "usecases.electronics.title": "Tracciabilità dei Componenti Critici",
    "usecases.electronics.desc": "Nel settore dell'elettronica, la gestione della supply chain è complessa e globale. TRUSTUP garantisce la tracciabilità completa di ogni componente critico, dai semiconduttori ai circuiti integrati, assicurando conformità normativa e autenticità del prodotto.",
    "usecases.electronics.items": [
      "Tracciabilità completa dei componenti critici e dei semiconduttori",
      "Certificazione automatica dell'origine e dell'autenticità",
      "Gestione della conformità RoHS e REACH",
      "Prevenzione dei componenti contraffatti e ricondizionati"
    ],
    "usecases.cosmetics.badge": "Cosmetica",
    "usecases.cosmetics.title": "Trasparenza e Autenticità del Brand",
    "usecases.cosmetics.desc": "Nel settore cosmetico, la fiducia del consumatore è tutto. TRUSTUP garantisce l'origine naturale degli ingredienti e protegge il brand dalla contraffazione.",
    "usecases.cosmetics.items": [
      "Tracciabilità della filiera bio e naturale",
      "Protezione anti-contraffazione con NFC/QR",
      "Certificazione Vegan e Cruelty-Free verificabile",
      "Engagement diretto col consumatore"
    ],
    "usecases.machinery.badge": "OEM & Impianti",
    "usecases.machinery.title": "Equipment-as-a-Service",
    "usecases.machinery.desc": "Trasforma la vendita del macchinario in un servizio ricorrente. TRUSTUP certifica l'uso effettivo, le manutenzioni e l'autenticità dei ricambi installati, abilitando modelli Pay-per-Use sicuri.",
    "usecases.machinery.items": [
      "Modelli di business Pay-per-Use certificati",
      "Protezione della proprietà intellettuale (IP)",
      "Tracciabilità dei ricambi originali",
      "Libretto di impianto digitale condiviso"
    ],
    "usecases.manu.badge": "Manufacturing",
    "usecases.manu.title": "Smart Factory & Equipment",
    "usecases.manu.desc": "Per i produttori di macchinari industriali, il Digital Twin è la chiave per abilitare nuovi modelli di business come Equipment-as-a-Service.",
    "usecases.manu.items": [
      "Registro digitale delle manutenzioni e riparazioni",
      "Certificazione automatica dei collaudi",
      "Accesso rapido alla documentazione tecnica in campo",
      "Protezione della proprietà intellettuale dei disegni CAD"
    ],
    "usecases.certs.badge": "Certificazioni",
    "usecases.certs.title": "Gestione Qualità & Audit",
    "usecases.certs.desc": "Semplifica drasticamente il processo di audit e certificazione ISO. Non più caccia ai documenti cartacei prima dell'ispezione.",
    "usecases.certs.corporate.title": "Certificazioni Aziendali",
    "usecases.certs.corporate.items": [
      "ISO 9001 (Qualità)",
      "ISO 14001 (Ambiente)",
      "ISO 45001 (Sicurezza)",
      "Responsabilità Sociale"
    ],
    "usecases.certs.process.title": "Certificazioni di Processo",
    "usecases.certs.process.items": [
      "Audit di produzione",
      "Controllo qualità in linea",
      "Manutenzione predittiva",
      "Efficienza energetica"
    ],
    "usecases.certs.supplier.title": "Certificazioni Fornitori",
    "usecases.certs.supplier.items": [
      "Qualifica fornitori",
      "Tracciabilità materie prime",
      "Compliance etica",
      "Audit della supply chain"
    ],
    "usecases.certs.material.title": "Certificazioni Materiali",
    "usecases.certs.material.items": [
      "Schede tecniche",
      "Test di laboratorio",
      "Origine controllata",
      "Sostenibilità materiali"
    ],
    "usecases.cta.title": "Hai un caso d'uso specifico?",
    "usecases.cta.button": "Contattaci",

    // Technology Overview Page
    "tech.overview.hero.title": "Tecnologia Trustless",
    "tech.overview.hero.subtitle": "Architettura decentralizzata, standard aperti e crittografia avanzata per garantire l'integrità dei dati senza intermediari.",
    "tech.overview.stack.did.title": "Decentralized Identity (DID)",
    "tech.overview.stack.did.desc": "Ogni asset riceve un'identità sovrana basata su standard W3C. Questo ID è indipendente da qualsiasi registro centralizzato e rimane sotto il controllo del proprietario dell'asset.",
    "tech.overview.stack.vc.title": "Verifiable Credentials (VC)",
    "tech.overview.stack.vc.desc": "I dati non sono semplici record database, ma attestazioni firmate crittograficamente. Chiunque può verificare l'autenticità e l'integrità dei dati senza contattare l'emittente.",
    "tech.overview.stack.sc.title": "Smart Contracts",
    "tech.overview.stack.sc.desc": "Logica di business eseguita automaticamente su blockchain. Gestisce regole di accesso, trasferimenti di proprietà e validazione di eventi in modo trasparente e immutabile.",
    "tech.overview.arch.title": "Architettura Ibrida",
    "tech.overview.arch.desc": "Combiniamo la velocità e scalabilità dei database tradizionali per i dati non critici con la sicurezza della blockchain per i dati di verifica.",
    "tech.overview.arch.offchain.title": "Off-Chain Storage",
    "tech.overview.arch.offchain.desc": "Dati voluminosi (immagini, CAD, documenti) salvati su storage distribuito (IPFS) o cloud sicuro, referenziati tramite hash.",
    "tech.overview.arch.onchain.title": "On-Chain Verification",
    "tech.overview.arch.onchain.desc": "Solo le \"impronte digitali\" (hash) e le prove crittografiche vengono salvate su blockchain, garantendo privacy e performance.",
    "tech.overview.cta.title": "Approfondisci la tecnologia",
    "tech.overview.cta.button": "Documentazione Tecnica",

    // Technology Page (Detailed)
    "tech.hero.title": "Tecnologia Trustless",
    "tech.hero.subtitle": "Architettura decentralizzata, standard aperti e crittografia avanzata.",
    "tech.did.title": "Identità Decentralizzata (DID)",
    "tech.did.desc": "Identificatori univoci globali che non dipendono da autorità centrali.",
    "tech.vc.title": "Credenziali Verificabili (VC)",
    "tech.vc.desc": "Attestazioni digitali firmate crittograficamente, verificabili istantaneamente.",
    "tech.sc.title": "Smart Contracts",
    "tech.sc.desc": "Logica di business eseguita automaticamente su blockchain.",
    "tech.interop.title": "Interoperabilità & Compliance",
    "tech.interop.desc": "Progettato per integrarsi con i sistemi esistenti e rispettare le normative.",
    "tech.interop.api.title": "API REST & GraphQL",
    "tech.interop.api.desc": "Integrazione facile con ERP, MES e sistemi legacy.",
    "tech.interop.gaiax.title": "GAIA-X Ready",
    "tech.interop.gaiax.desc": "Conforme agli standard europei per la sovranità dei dati.",
    "tech.interop.gdpr.title": "GDPR Compliant",
    "tech.interop.gdpr.desc": "Privacy by design e gestione granulare dei consensi.",

    // Open Source Page
    "opensource.hero.badge": "Open Standards",
    "opensource.hero.title": "Open Source & Standard",
    "opensource.hero.subtitle": "Crediamo che la fiducia debba essere costruita su fondamenta aperte. Per questo adottiamo e contribuiamo ai principali standard globali.",
    "opensource.global.title": "Standard Globali",
    "opensource.global.intro": "Adottiamo protocolli riconosciuti a livello internazionale per garantire che i dati dei tuoi asset siano universalmente leggibili, interoperabili e sicuri, indipendentemente dalla piattaforma utilizzata.",
    "opensource.eu.title": "Standard Europei",
    "opensource.eu.intro": "Siamo allineati con le direttive dell'Unione Europea per la sovranità dei dati e l'identità digitale, assicurando che la tua azienda sia pronta per le normative attuali e future.",

    "opensource.standards.w3c.title": "Identità Sovrana",
    "opensource.standards.w3c.desc": "Utilizziamo identificatori decentralizzati (DID) e credenziali verificabili (VC) per dare agli asset un'identità digitale autonoma, sicura e portabile, eliminando la dipendenza da registri centralizzati proprietari.",
    "opensource.standards.unece.title": "Digitalizzazione del Commercio",
    "opensource.standards.unece.desc": "Implementiamo modelli dati standard per la supply chain internazionale, facilitando lo scambio di documenti commerciali e logistici in formato digitale verificabile tra partner globali.",
    "opensource.standards.gs1.title": "Tracciabilità Globale",
    "opensource.standards.gs1.desc": "Integriamo lo standard GS1 Digital Link per connettere i prodotti fisici al loro gemello digitale, permettendo una scansione universale (es. QR Code) che funziona ovunque nel mondo.",
    "opensource.standards.gleif.title": "Identità Legale Certificata",
    "opensource.standards.gleif.desc": "Colleghiamo l'identità degli asset all'identità legale dell'azienda (LEI), creando una catena di fiducia verificabile che certifica chi è il proprietario o il produttore di un bene.",
    "opensource.standards.iso.title": "Qualità e Sicurezza",
    "opensource.standards.iso.desc": "Le nostre strutture dati rispettano gli standard ISO per la gestione della qualità e della sicurezza delle informazioni, garantendo che i processi digitali siano robusti e conformi alle best practice industriali.",

    "opensource.standards.gaiax.title": "Sovranità dei Dati",
    "opensource.standards.gaiax.desc": "Aderiamo ai principi di GAIA-X per creare ecosistemi di dati aperti e trasparenti, dove le aziende mantengono il controllo completo su dove risiedono i propri dati e chi può accedervi.",
    "opensource.standards.nis2.title": "Cybersecurity Compliance",
    "opensource.standards.nis2.desc": "La piattaforma è progettata secondo i requisiti della direttiva NIS2, offrendo livelli avanzati di sicurezza informatica per proteggere le infrastrutture critiche e i dati sensibili dell'industria.",
    "opensource.standards.eidas.title": "Fiducia Digitale UE",
    "opensource.standards.eidas.desc": "Supportiamo il framework eIDAS 2.0 e l'EU Digital Identity Wallet, permettendo l'uso di identità digitali riconosciute legalmente in tutta Europa per firmare e validare transazioni.",
    "opensource.standards.eidas2.title": "eIDAS 2.0",
    "opensource.standards.eidas2.desc": "Piena compatibilità con il nuovo regolamento europeo sull'identità digitale.",
    "opensource.european.intro": "Siamo allineati con le direttive dell'Unione Europea per la sovranità dei dati e l'identità digitale.",

    // About Page
    "about.hero.title": "Costruiamo la Fiducia Digitale",
    "about.hero.subtitle": "La nostra missione è rendere ogni asset fisico verificabile, sicuro e trasparente attraverso la tecnologia.",
    "about.mission.title": "La Nostra Missione",
    "about.mission.desc": "Abilitare un'economia industriale dove la fiducia è nativa nel dato, non nell'intermediario.",
    "about.vision.title": "La Nostra Visione",
    "about.vision.desc": "Un mondo dove ogni prodotto racconta la sua storia vera, verificabile da chiunque, ovunque.",
    "about.team.title": "Il Team",
    "about.team.desc": "Esperti di blockchain, ingegneri industriali e visionari del digitale uniti per trasformare l'industria.",

    "about.values.title": "I Nostri Valori",
    "about.values.subtitle": "Principi fondamentali che guidano ogni nostra decisione e riga di codice.",
    "about.values.security": "Sicurezza Prima di Tutto",
    "about.values.security.desc": "Non scendiamo a compromessi sulla protezione dei dati. Crittografia avanzata e standard militari sono il nostro punto di partenza.",
    "about.values.collab": "Collaborazione Aperta",
    "about.values.collab.desc": "Crediamo nell'open source e negli standard condivisi. La vera innovazione nasce dalla cooperazione, non dai silos.",
    "about.values.innovation": "Innovazione Pragmatica",
    "about.values.innovation.desc": "Non seguiamo le mode. Implementiamo tecnologie di frontiera solo quando portano un valore tangibile e misurabile.",
    "about.cta.title": "Unisciti alla Rivoluzione Industriale",
    "about.cta.button": "Lavora con Noi",

    // Contact Page
    "contact.hero.title": "Parla con Noi",
    "contact.hero.subtitle": "Siamo qui per rispondere alle tue domande e guidarti nella trasformazione digitale.",
    "contact.info.email": "Email",
    "contact.form.firstName": "Nome",
    "contact.form.lastName": "Cognome",
    "contact.form.company": "Azienda",
    "contact.form.email": "Email Aziendale",
    "contact.form.sector": "Settore",
    "contact.form.sector.placeholder": "Seleziona un settore",
    "contact.form.sector.auto": "Automotive",
    "contact.form.sector.manu": "Manifatturiero",
    "contact.form.sector.aero": "Aerospaziale",
    "contact.form.sector.other": "Altro",
    "contact.form.message": "Messaggio",
    "contact.form.message.placeholder": "Come possiamo aiutarti?",
    "contact.form.privacy": "Ho letto e accetto la Privacy Policy",
    "contact.form.submit": "Invia Messaggio",
    "contact.form.submitting": "Invio in corso...",
    "contact.form.success": "Messaggio inviato con successo! Ti risponderemo a breve.",

    // Configurator Page
    "configurator.back": "Torna alla Dashboard",
    "configurator.logout": "Esci",
    "configurator.title": "Configuratore Prezzi TRUSTUP",
    "configurator.subtitle": "Configura i servizi, stima i volumi e ottieni un preventivo personalizzato",
    "configurator.mandatory": "OBBLIGATORIO",
    "configurator.oneTime": "una tantum",
    "configurator.perQuarter": "/ trimestre",
    "configurator.includes": "Include:",

    // Services
    "configurator.services.saas.name": "Canone SaaS Piattaforma",
    "configurator.services.saas.desc": "Accesso alla piattaforma TRUSTUP con tutte le funzionalità base (sempre incluso)",
    "configurator.services.saas.inc1": "Accesso piattaforma web",
    "configurator.services.saas.inc2": "Gestione certificati digitali",
    "configurator.services.saas.inc3": "Storage 100GB",
    "configurator.services.saas.inc4": "Supporto tecnico base",
    "configurator.services.saas.inc5": "Aggiornamenti piattaforma",

    "configurator.services.startup.name": "Attivazione TRUSTUP",
    "configurator.services.startup.desc": "Setup completo del tenant, configurazione, onboarding e formazione operativa",
    "configurator.services.startup.inc1": "Setup tenant e ruoli",
    "configurator.services.startup.inc2": "Modellazione identità digitale asset",
    "configurator.services.startup.inc3": "Definizione tassonomie certificati",
    "configurator.services.startup.inc4": "Impostazione Smart Contract",
    "configurator.services.startup.inc5": "Import iniziale dati",
    "configurator.services.startup.inc6": "Formazione personale",

    "configurator.services.vlei.name": "Identità Legale vLEI",
    "configurator.services.vlei.desc": "Integrazione vLEI (verifiable Legal Entity Identifier) per identità legale blockchain",
    "configurator.services.vlei.inc1": "Creazione DID aziendale",
    "configurator.services.vlei.inc2": "Associazione vLEI",
    "configurator.services.vlei.inc3": "Notarizzazione su blockchain",
    "configurator.services.vlei.inc4": "Configurazione verifica pubblica",

    "configurator.services.api.name": "Integrazione API Enti",
    "configurator.services.api.desc": "Connessione con registri e enti esterni per verifiche automatiche (include canone trimestrale €450)",
    "configurator.services.api.inc1": "Setup connettori custom",
    "configurator.services.api.inc2": "Integrazione registri esterni",
    "configurator.services.api.inc3": "Verifiche automatiche",
    "configurator.services.api.inc4": "Sincronizzazione dati",
    "configurator.services.api.inc5": "+ Canone Add-on API: €450/trimestre",

    // Service Selector
    "configurator.selector.title": "Seleziona i Servizi",
    "configurator.selector.base": "Servizi Base",
    "configurator.selector.addons": "Moduli Aggiuntivi (Opzionali)",

    // Volume Estimator
    "configurator.volumes.title": "Stima i Volumi Annuali",
    "configurator.volumes.totalCredits": "Crediti Totali Stimati",
    "configurator.volumes.suggested": "Pacchetto Suggerito: {name}",
    "configurator.volumes.suggestedDesc": "{credits} crediti a €{price} (€{pricePerCredit}/credito)",
    "configurator.volumes.remaining": "+{remaining} residui",
    "configurator.volumes.howItWorks": "Come funziona:",
    "configurator.volumes.howItWorksDesc": "Ogni operazione consuma 1 credito. I crediti non scadono mai e si accumulano nel tuo account. Puoi acquistare pacchetti aggiuntivi in qualsiasi momento.",

    "configurator.volumes.certificates": "Certificati Singoli",
    "configurator.volumes.certificates.desc": "Numero di certificati individuali da notarizzare annualmente",
    "configurator.volumes.dossiers": "Dossier Completi",
    "configurator.volumes.dossiers.desc": "Numero di dossier (raccolte di certificati) da notarizzare",
    "configurator.volumes.updates": "Aggiornamenti",
    "configurator.volumes.updates.desc": "Numero di aggiornamenti/nuove versioni di certificati esistenti",
    "configurator.volumes.revokes": "Revoche",
    "configurator.volumes.revokes.desc": "Numero di revoche di certificati previste",
    "configurator.volumes.milestones": "Event Milestone",
    "configurator.volumes.milestones.desc": "Numero di eventi/milestone da tracciare (opzionale)",
    "configurator.volumes.did": "Registrazioni DID Prodotti",
    "configurator.volumes.did.desc": "Numero di identità digitali prodotto da registrare",

    // Credit Pack Selector
    "configurator.credits.title": "Seleziona il Pacchetto Crediti",
    "configurator.credits.estimated": "Crediti Stimati Necessari",
    "configurator.credits.suggested": "Consigliato",
    "configurator.credits.credits": "crediti",
    "configurator.credits.perCredit": "/credito",
    "configurator.credits.savings": "Risparmi {savings}%",
    "configurator.credits.insufficient": "Crediti insufficienti per i volumi stimati",
    "configurator.credits.remaining": "+{remaining} crediti residui",
    "configurator.credits.note": "I crediti non scadono mai e si accumulano nel tuo account. Puoi acquistare pacchetti aggiuntivi in qualsiasi momento. Ogni operazione (certificato, dossier, aggiornamento, revoca, etc.) consuma 1 credito.",

    // Pricing Summary
    "configurator.summary.title": "Riepilogo Preventivo",
    "configurator.summary.subtitle": "Configurazione completa per il primo anno di servizio",
    "configurator.summary.setup.title": "Costi di Setup",
    "configurator.summary.setup.subtitle": "Investimento iniziale una tantum",
    "configurator.summary.setup.startup": "Attivazione TRUSTUP",
    "configurator.summary.setup.vlei": "Identità Legale vLEI",
    "configurator.summary.setup.api": "Integrazione API Enti",
    "configurator.summary.setup.total": "Totale Setup",

    "configurator.summary.recurring.title": "Canoni Ricorrenti",
    "configurator.summary.recurring.subtitle": "Costi operativi annuali",
    "configurator.summary.recurring.base": "Canone Base SaaS (€{monthly}/mese)",
    "configurator.summary.recurring.vlei": "Add-on vLEI (€{monthly}/mese)",
    "configurator.summary.recurring.api": "Add-on API (€{monthly}/mese)",
    "configurator.summary.recurring.year1": "Totale Anno 1",
    "configurator.summary.recurring.year2": "Proiezione Anno 2 (M2 +{rate}%)",
    "configurator.summary.recurring.satoshi": "Equivalente Satoshi (fisso)",

    "configurator.summary.credits.title": "Crediti Blockchain",
    "configurator.summary.credits.subtitle": "Pacchetto operazioni on-chain",
    "configurator.summary.credits.selected": "Pacchetto Selezionato",
    "configurator.summary.credits.estimated": "Crediti Stimati Necessari",
    "configurator.summary.credits.cost": "Costo Crediti",

    // Chiavi brevi per PricingSummary
    "configurator.summary.setup": "Costi di Setup",
    "configurator.summary.setupDesc": "Investimento iniziale una tantum",
    "configurator.summary.recurring": "Canoni Ricorrenti",
    "configurator.summary.recurringDesc": "Costi operativi annuali",
    "configurator.summary.year1": "Totale Anno 1",
    "configurator.summary.year2Projection": "Proiezione Anno 2 (M2 +{rate}%)",
    "configurator.summary.satoshiFixed": "Equivalente Satoshi (fisso)",
    "configurator.summary.credits": "Crediti Blockchain",
    "configurator.summary.creditsDesc": "Pacchetto operazioni on-chain",
    "configurator.summary.selectedPack": "Pacchetto Selezionato",
    "configurator.summary.estimatedCredits": "Crediti Stimati Necessari",
    "configurator.summary.creditsCost": "Costo Crediti",
    "configurator.summary.totalInvestment": "Investimento Totale",
    "configurator.summary.firstYearComplete": "Primo Anno Completo",
    "configurator.summary.initialSetup": "Setup Iniziale",
    "configurator.summary.year1Fees": "Canoni Anno 1",
    "configurator.summary.blockchainCredits": "Crediti Blockchain",
    "configurator.summary.vleiActions": "Azioni vLEI",
    "configurator.summary.vleiActionsDesc": "Costi per aggiornamenti identità legale vLEI",
    "configurator.summary.vleiUpdatesPerYear": "Aggiornamenti/Anno",
    "configurator.summary.vleiPricePerAction": "Prezzo per Azione",
    "configurator.summary.vleiActionsCost": "Costo Azioni vLEI",
    "configurator.summary.selectedCurrency": "Valuta Selezionata:",
    "configurator.summary.eurDesc": "Canoni rivalutati annualmente (M2 +{rate}%)",
    "configurator.summary.btcDesc": "Canoni fissi in satoshi ({sats} sats/anno)",
    "configurator.summary.downloadPDF": "Scarica PDF",
    "configurator.summary.saveConfig": "Salva Configurazione",
    "configurator.summary.requestContact": "Richiedi Contatto",

    "configurator.summary.total.title": "Investimento Totale",
    "configurator.summary.total.year1": "Primo Anno Completo",
    "configurator.summary.total.setup": "Setup Iniziale",
    "configurator.summary.total.recurring": "Canoni Anno 1",
    "configurator.summary.total.credits": "Crediti Blockchain",
    "configurator.summary.total.vleiActions": "Azioni vLEI",
    "configurator.summary.total.currency": "Valuta Selezionata:",
    "configurator.summary.total.eurDesc": "Canoni rivalutati annualmente (M2 +{rate}%)",
    "configurator.summary.total.btcDesc": "Canoni fissi in satoshi ({sats} sats/anno)",

    "configurator.summary.download": "Scarica PDF",
    "configurator.summary.save": "Salva Configurazione",
    "configurator.summary.contact": "Richiedi Contatto"
  },
  en: {
    // Navigation
    "nav.platform": "Platform",
    "nav.benefits": "Benefits",
    "nav.useCases": "Use Cases",
    "nav.technology": "Technology",
    "nav.opensource": "Open Source",
    "nav.company": "Company",
    "nav.about": "About Us",
    "nav.contact": "Contact",
    "nav.demo": "Request Demo",
    "nav.overview": "Overview",
    "nav.dap": "Digital Asset Passport",
    "nav.vdl": "Verified Data Layer",
    "nav.sc": "Smart Contracts",
    "nav.legal": "Legal",
    "nav.privacy": "Privacy Policy",
    "nav.cookie": "Cookie Policy",
    "nav.pricing": "Pricing",
    "nav.login": "Login",
    "footer.desc": "Enterprise Platform for Digital Twin and Digital Identity of industrial assets. Security, traceability, and regulatory compliance.",
    "footer.rights": "\u00a9 2025 TRUSTUP. All rights reserved.",

    // Pricing Page
    "pricing.hero.badge": "Pricing Protocol v1.0",
    "pricing.hero.title.part1": "Choose your",
    "pricing.hero.title.highlight1": "Currency",
    "pricing.hero.title.part2": "Define your",
    "pricing.hero.title.highlight2": "Future",
    "pricing.hero.subtitle": "A revolutionary dual model: stability linked to the real economy or cryptographic protection from inflation. Simulate your ideal scenario.",
    "pricing.hero.cta": "Access Reserved Area",
    "pricing.hero.demo": "Request Demo",
    "pricing.value.stability.title": "Guaranteed Stability",
    "pricing.value.stability.desc": "Annual revaluation linked to the M2 index to protect real value.",
    "pricing.value.protection.title": "Inflation Protection",
    "pricing.value.protection.desc": "Bitcoin option for long-term cryptographic protection.",
    "pricing.value.flexibility.title": "Total Flexibility",
    "pricing.value.flexibility.desc": "Choose the model that best suits your business strategy.",
    "pricing.calculator.title": "Simulate Your Scenario",
    "pricing.calculator.subtitle": "Use the calculator to compare the two pricing models and find the one that best suits your needs.",
    "pricing.calculator.liveMode": "Live BTC Mode",
    "pricing.calculator.howItWorks": "How does it work?",
    "pricing.calculator.eurDesc": "Revalued annually based on M2 growth (USA+EU).",
    "pricing.calculator.btcDesc": "The number of satoshi is fixed forever. The € value changes.",
    "pricing.calculator.note": "The choice is binding for the duration of the contract.",
    "pricing.chart.title": "5-Year Projection",
    "pricing.cta.title": "Ready to Start?",
    "pricing.cta.subtitle": "Register to access the full configurator and create your personalized configuration.",

    // Login Page
    "login.back": "Back to Home",
    "login.title.part1": "Access the",
    "login.title.part2": "Reserved Area",
    "login.subtitle": "Sign in with your credentials to manage your configurations",
    "login.email": "Email",
    "login.email.placeholder": "E.g. john.doe@company.com",
    "login.password": "Password",
    "login.password.placeholder": "Enter your password",
    "login.submit": "Sign In",
    "login.loading": "Signing in...",
    "login.noAccount": "Don't have an account?",
    "login.register": "Request Access",
    "login.error.invalid": "Invalid email or password",
    "login.error.generic": "An error occurred. Please try again later.",

    // Register Page
    "register.back": "Back to Home",
    "register.title.part1": "Request",
    "register.title.part2": "Access",
    "register.subtitle": "Fill in the form to request access to the platform",
    "register.name": "Full Name",
    "register.name.placeholder": "E.g. John Doe",
    "register.email": "Business Email",
    "register.email.placeholder": "E.g. john.doe@company.com",
    "register.company": "Company Name",
    "register.company.placeholder": "E.g. Acme Corporation",
    "register.phone": "Phone",
    "register.phone.placeholder": "E.g. +1 555 123 4567",
    "register.password": "Password",
    "register.password.placeholder": "Minimum 6 characters",
    "register.confirmPassword": "Confirm Password",
    "register.confirmPassword.placeholder": "Repeat the password",
    "register.submit": "Request Access",
    "register.loading": "Sending request...",
    "register.hasAccount": "Already have an account?",
    "register.login": "Sign In",
    "register.error.passwordMismatch": "Passwords do not match",
    "register.error.passwordTooShort": "Password must be at least 6 characters",
    "register.error.generic": "An error occurred. Please try again later.",
    "register.success.title": "Request Sent!",
    "register.success.message": "Your access request has been sent. You will receive a confirmation email when your account is activated.",
    "register.success.login": "Go to Login",

    // Dashboard Page
    "dashboard.back": "Back to Home",
    "dashboard.welcome": "Welcome",
    "dashboard.subtitle": "Manage your configurations and access the pricing configurator.",
    "dashboard.configurator": "Pricing Configurator",
    "dashboard.configurator.desc": "Create and manage your dual-currency pricing configurations.",
    "dashboard.documents": "Documents",
    "dashboard.documents.desc": "View and download your contractual documents.",
    "dashboard.settings": "Settings",
    "dashboard.settings.desc": "Manage your account settings.",
    "dashboard.comingSoon": "Coming Soon",
    "dashboard.savedConfigs": "Saved Configurations",
    "dashboard.newConfig": "New Configuration",
    "dashboard.noConfigs": "You haven't saved any configurations yet.",
    "dashboard.createFirst": "Create your first configuration",
    "dashboard.editProfile": "Edit Profile",
    "dashboard.totalCost": "Total",
    "dashboard.setupCost": "Setup Costs",
    "dashboard.recurringCost": "Recurring Fees",
    "dashboard.annual": "annual",
    "dashboard.credits": "Blockchain Credits",
    "dashboard.creditsCost": "Blockchain Credits",
    "dashboard.vleiActions": "vLEI Actions",
    "dashboard.totalYear1": "Total Year 1",
    "dashboard.servicesIncluded": "Services Included",
    "dashboard.baseSaaS": "Base SaaS Fee",
    "dashboard.vleiAddon": "vLEI Add-on",
    "dashboard.apiAddon": "API Add-on",
    "dashboard.reopenConfig": "Reopen Configuration",
    "pricing.cta.register": "Register Now",
    "pricing.cta.contact": "Talk to an Expert",

    // Register Form (Pricing Page)
    "registerForm.badge": "TRUSTUP PRICING PROTOCOL v1.0",
    "registerForm.title": "Register to the",
    "registerForm.titleHighlight": "Reserved Area",
    "registerForm.subtitle": "Create your account to save and manage your configurations",
    "registerForm.firstName": "First Name",
    "registerForm.firstName.placeholder": "E.g. John",
    "registerForm.lastName": "Last Name",
    "registerForm.lastName.placeholder": "E.g. Doe",
    "registerForm.company": "Company",
    "registerForm.company.placeholder": "E.g. Acme Inc.",
    "registerForm.email": "Email",
    "registerForm.email.placeholder": "E.g. john.doe@company.com",
    "registerForm.password": "Password",
    "registerForm.password.placeholder": "Enter your password",
    "registerForm.submit": "Register",
    "registerForm.hasAccount": "Already have an account?",
    "registerForm.login": "Login",

    // Calculator Controls
    "calculator.title": "Simulation Parameters",
    "calculator.reset": "Reset to default values",
    "calculator.basePrice": "Monthly Base Fee (€)",
    "calculator.basePrice.desc": "The current price of the SaaS service in Euro.",
    "calculator.btcPrice": "Simulated Bitcoin Price (€)",
    "calculator.btcPrice.desc": "Simulate how the value changes if BTC rises or falls.",
    "calculator.m2Rate": "M2 Rate (USA+EU)",
    "calculator.m2Rate.desc": "Annual variation of the combined monetary mass.",
    "calculator.liveMode": "Live BTC Mode",

    // Pricing Cards
    "pricingCard.fiat.title": "Fiat Stability",
    "pricingCard.fiat.subtitle": "Price linked to the real economy (M2)",
    "pricingCard.btc.title": "Bitcoin Standard",
    "pricingCard.btc.subtitle": "Fixed price in satoshi forever",
    "pricingCard.monthlyFee": "Monthly Fee",
    "pricingCard.perMonth": "/month",
    "pricingCard.sats": "sats",
    "pricingCard.currentRate": "≈ €{amount} at current rate",
    "pricingCard.revaluation2026": "2026 Revaluation",
    "pricingCard.futurePrice": "Future Price (Estimate)",
    "pricingCard.fiat.desc": "The fee will increase by €{amount} based on M2 growth.",
    "pricingCard.btc.desc": "The number of satoshi will never change, regardless of Bitcoin price.",
    "pricingCard.selected": "Selected Plan",
    "pricingCard.select": "Select Plan",

    // Home
    "home.hero.badge": "Enterprise Digital Twin Platform",
    "home.hero.title": "Digital Twin & Verifiable Digital Identity for Industry",
    "home.hero.subtitle": "A digital replica of industrial processes built on verifiable data and credentials: certified assets and products, efficient automation, compliance and end-to-end supply-chain traceability.",
    "home.hero.cta": "Discover Platform",
    "home.hero.demo": "Request Demo",
    "home.scroll": "Scroll",

    "home.value.smartObject.title": "Smart Object",
    "home.value.smartObject.desc": "Identity + Ownership. Every asset gets a certain and immutable digital identifier.",
    "home.value.smartContract.title": "Smart Contract",
    "home.value.smartContract.desc": "Event Engine + Rules. Process automation with integrated validations and permissions.",
    "home.value.digitalTwin.title": "Digital Twin",
    "home.value.digitalTwin.desc": "Complete Virtual Replica. Static, dynamic, and historical data in a single digital passport.",

    "home.problem.title": "From State to Fact: Data Evolution",
      "home.problem.current.title": "The Problem Today",
      "home.problem.current.desc": "Current data management systems fail to meet the upcoming operational, communicative, regulatory, functional, and competitive context: data remains records and 'states', not facts (who did what, when, on which asset/batch, with what responsibility and proof).",
      "home.problem.current.list": [
        "Coherently connecting departments and processes (slower operations, difficult exception handling)",
        "Communicating reliable information to clients, suppliers, auditors, and partners (excessive reconciliation and disputes)",
        "Maintaining compliance proactively (reactive adjustments, increasing risk and costs)",
        "Transforming data into a commercial advantage (unmeasurable trust, slower qualifications and partnerships)"
      ],
      "home.problem.solution.title": "The TRUSTUP Solution",
      "home.problem.solution.desc": "TRUSTUP enables an event-driven model where every interaction with assets and processes becomes a verifiable operational fact, reusable across functions and shareable with the supply chain under clear rules.",
      "home.problem.solution.list": [
        "From record to fact: actions become operational evidence, not just system entries",
        "Supply chain communication: portable and controlled data access, reducing rework and ambiguity between actors",
        "Compliance-by-design: processes generating 'compliance-ready' data, reducing audit times and risks",
        "Decision speed: less friction between departments, more operational continuity and rapid change management",
        "Trust as a competitive advantage: measurable transparency and credibility accelerating qualification, sales, and partnerships",
        "Digital identity and responsibility: clarity on who generates data and with what responsibility, for scalable collaboration"
      ],

    "home.industries.title": "Solutions for Industry",
    "home.industries.subtitle": "Scalable technology designed for the critical needs of high-complexity sectors.",
    "home.industries.auto.title": "Automotive",
    "home.industries.auto.desc": "Component traceability, IATF 16949 certifications, and complete supply chain visibility.",
    "home.industries.manu.title": "Manufacturing",
    "home.industries.manu.desc": "Machine Digital Twin for predictive maintenance and automated quality certification.",
    "home.industries.medical.title": "Medical",
    "home.industries.medical.desc": "Complete digital dossier for MDR compliance and device traceability.",
    "home.industries.electronics.title": "Electronics",
    "home.industries.electronics.desc": "Critical component traceability and origin certification against counterfeiting.",
    "home.industries.cosmetics.title": "Cosmetics",
    "home.industries.cosmetics.desc": "Ingredient traceability, anti-counterfeiting for luxury brands, and regulatory compliance.",
    "home.industries.machinery.title": "Machinery & Plants",
    "home.industries.machinery.desc": "Digital Machine Passport, servitization, and certified original spare parts.",
    "home.industries.cta": "Explore Solutions",
    "home.cta.title": "Ready to digitize your assets?",
    "home.cta.subtitle": "Request a dedicated deep dive with our experts to analyze your specific use case.",
    "home.cta.button": "Talk to an Expert",

    // Platform
    "platform.hero.title": "The TRUSTUP Platform",
    "platform.hero.subtitle": "A complete ecosystem for creating, managing, and sharing secure and verifiable Digital Asset Passports.",
    "platform.core.badge": "Core Architecture",
    "platform.core.title": "Digital Asset Passport",
    "platform.core.desc": "The heart of the platform is the Digital Asset Passport (DAP), a secure container that aggregates three fundamental types of data for every industrial asset.",
    "platform.core.static.title": "Static Data",
    "platform.core.static.desc": "Identity, ownership, technical specifications, and manuals.",
    "platform.core.dynamic.title": "Dynamic Data",
    "platform.core.dynamic.desc": "Real-time status, IoT telemetry, and operational parameters.",
    "platform.core.history.title": "Historical Data",
    "platform.core.history.desc": "Maintenance, events, certifications, and immutable audit trail.",

    "platform.vdl.title": "Verified Data Layer",
    "platform.vdl.subtitle": "A layer of cryptographic trust ensuring the integrity and origin of every piece of information.",
    "platform.vdl.did.title": "DID / Unique ID",
    "platform.vdl.did.desc": "Decentralized identifiers compliant with W3C standards for sovereign asset identity.",
    "platform.vdl.vc.title": "Verifiable Credentials",
    "platform.vdl.vc.desc": "Cryptographically signed digital attestations proving authenticity and compliance.",
    "platform.vdl.events.title": "Events & Timeline",
    "platform.vdl.events.desc": "Immutable registry of every interaction, maintenance, or status change throughout the lifecycle.",
    "platform.vdl.access.title": "DPP Access",
    "platform.vdl.access.desc": "Immediate access to the Digital Product Passport via QR Code or secure Link.",

    "platform.features.title": "Enterprise Features",
    "platform.features.list.1": "Multi-channel Upload (API/Web)",
    "platform.features.list.2": "Full-text Search and Advanced Filters",
    "platform.features.list.3": "Versioning and Compliant Storage",
    "platform.features.list.4": "Configurable Assets and Relationships",
    "platform.features.list.5": "Sharing with Granular Permissions",
    "platform.features.list.6": "Blockchain Notarization",

    // Digital Asset Passport Page
    "dap.hero.badge": "Platform Module",
    "dap.hero.title": "Digital Asset Passport",
    "dap.hero.subtitle": "Complete and secure digital identity for every physical asset. A single point of truth aggregating static, dynamic, and historical data.",
    "dap.concept.title": "Beyond a simple database",
    "dap.concept.desc": "The Digital Asset Passport (DAP) is not just a document archive. It is a living, interactive representation of the asset, built on international standards to ensure data interoperability and longevity.",
    "dap.data.static.title": "Static Data (Master Data)",
    "dap.data.static.desc": "Technical specs, CAD drawings, user manuals, BOM (Bill of Materials), and initial compliance info.",
    "dap.data.dynamic.title": "Dynamic Data (IoT & Status)",
    "dap.data.dynamic.desc": "Integration with sensors and MES systems to log operating hours, cycles, consumption, and real-time parameters.",
    "dap.data.history.title": "Historical Data (Lifecycle)",
    "dap.data.history.desc": "Immutable log of maintenance, repairs, software updates, ownership changes, and compliance audits.",
    "dap.features.title": "Key Features",
    "dap.features.access.title": "Universal Accessibility",
    "dap.features.access.desc": "Data access via QR Code, NFC, or secure Link, with differentiated permission levels for maintainers, auditors, and customers.",
    "dap.features.modular.title": "Modular Structure",
    "dap.features.modular.desc": "The passport grows with the asset. Add new data modules over time without breaking existing compatibility.",
    "dap.features.portable.title": "Data Portability",
    "dap.features.portable.desc": "Export the entire passport in standard formats (JSON-LD, certified PDF) for maximum interoperability.",
    "dap.cta.title": "Start creating your Digital Passports",
    "dap.cta.button": "Request Demo",

    // Verified Data Layer Page
    "vdl.hero.badge": "Platform Module",
    "vdl.hero.title": "Verified Data Layer",
    "vdl.hero.subtitle": "The trust infrastructure transforming simple data into irrefutable digital proofs. Cryptographic security, sovereign identity, and immutability.",
    "vdl.tech.did.title": "DID (Decentralized Identifiers)",
    "vdl.tech.did.desc": "Global unique identifiers (W3C Standard) independent of central authorities. Asset identity is controlled exclusively by the owner via cryptographic keys.",
    "vdl.tech.vc.title": "Verifiable Credentials",
    "vdl.tech.vc.desc": "The standard format for digital attestations. Allows verification of issuer (e.g., certification body), data integrity, and validity.",
    "vdl.tech.blockchain.title": "Blockchain Notarization",
    "vdl.tech.blockchain.desc": "A distributed, immutable ledger serving as a \"trust anchor\". Used for secure timestamping and ensuring asset history cannot be rewritten.",
    "vdl.verify.title": "How does verification work?",
    "vdl.verify.desc": "The verification process is instant and mathematical, eliminating the need to blindly trust easily forgeable paper documents or PDFs.",
    "vdl.verify.step1.title": "Issuer Verification",
    "vdl.verify.step1.desc": "The system checks the issuer's digital signature (e.g., analysis lab) via their public DID.",
    "vdl.verify.step2.title": "Integrity Verification",
    "vdl.verify.step2.desc": "The document hash is recalculated to ensure not a single bit has been modified since signing.",
    "vdl.verify.step3.title": "Status Verification",
    "vdl.verify.step3.desc": "Real-time blockchain check to verify the credential hasn't been revoked.",
    "vdl.cta.title": "Protect your critical data",
    "vdl.cta.button": "Talk to an Expert",

    // Smart Contracts Page
    "sc.hero.badge": "Platform Module",
    "sc.hero.title": "Smart Contracts",
    "sc.hero.subtitle": "Industrial process automation based on immutable code. Certain rules, guaranteed execution, and zero intermediaries.",
    "sc.cases.title": "Industrial Process Automation",
    "sc.cases.desc": "TRUSTUP Smart Contracts allow defining business rules executed automatically upon certain conditions, without human error or manipulation.",
    "sc.cases.supply.title": "Automatic Supply Chain",
    "sc.cases.supply.desc": "\"If the batch passes quality control and transport temperature remained under 4°C, then release payment to supplier and transfer digital ownership.\"",
    "sc.cases.maint.title": "Supply Chain Integration & Interoperability",
    "sc.cases.maint.desc": "\"If compliance certificate is valid and product is received in warehouse, then automatically update inventory and notify ERP system.\"",
    "sc.benefits.speed.title": "Speed",
    "sc.benefits.speed.desc": "Immediate execution once criteria are met, eliminating days of waiting for manual approvals.",
    "sc.benefits.security.title": "Security",
    "sc.benefits.security.desc": "Smart Contract code is immutable and visible, ensuring rules cannot be arbitrarily changed.",
    "sc.benefits.efficiency.title": "Efficiency",
    "sc.benefits.efficiency.desc": "Drastic reduction of administrative and reconciliation costs thanks to automation.",
    "sc.benefits.cost.title": "Reduced Costs",
    "sc.benefits.cost.desc": "Elimination of intermediaries and error-prone manual processes.",
    "sc.cta.title": "Automate your processes",
    "sc.cta.button": "Request Demo",

    // Benefits Page
    "benefits.hero.title": "Competitive Advantage",
    "benefits.hero.subtitle": "Digital transition is not just technology, it's a strategy to position your company at the forefront.",
    "benefits.operational.title": "Operational Benefits",
    "benefits.operational.efficiency.title": "Production Efficiency",
    "benefits.operational.efficiency.desc": "Drastic reduction of manual errors, rework, and scrap. Fewer line stoppages thanks to data-driven predictive maintenance.",
    "benefits.operational.audit.title": "Audit Speed",
    "benefits.operational.audit.desc": "Audit times reduced by up to 70%. Evidence is ready, organized, and verified in the Digital Asset Passport.",
    "benefits.operational.traceability.title": "Total Traceability",
    "benefits.operational.traceability.desc": "End-to-end supply chain visibility. Always know where every component is and where it comes from.",
    "benefits.strategic.title": "Strategic Benefits",
    "benefits.strategic.compliance.title": "Regulatory Compliance",
    "benefits.strategic.compliance.desc": "Automatic compliance with EU regulations (e.g., Battery Regulation, ESPR) and industry standards (e.g., IATF 16949).",
    "benefits.strategic.brand.title": "Brand Reputation",
    "benefits.strategic.brand.desc": "Transparency as added value for the end customer. Demonstrate the quality and sustainability of your products.",
    "benefits.strategic.data.title": "Data Monetization",
    "benefits.strategic.data.desc": "Transform product data into new revenue streams, offering value-added services based on the Digital Twin.",

    "benefits.business.title": "Business Impact",
    "benefits.business.ecosystem.title": "Connected Ecosystem",
    "benefits.business.ecosystem.desc": "Seamless integration with partners, suppliers, and customers in a single trust network.",
    "benefits.business.opportunity.title": "New Opportunities",
    "benefits.business.opportunity.desc": "Unlock innovative business models like Product-as-a-Service and Pay-per-Use.",
    "benefits.business.resilience.title": "Operational Resilience",
    "benefits.business.resilience.desc": "Greater adaptability to supply chain disruptions thanks to total visibility.",

    "benefits.roi.title": "Return on Investment",
    "benefits.roi.subtitle": "Measurable results justifying technology adoption.",
    "benefits.roi.efficiency.value": "+40%",
    "benefits.roi.efficiency.desc": "Operational Efficiency",
    "benefits.roi.time.value": "-70%",
    "benefits.roi.time.desc": "Audit Time",
    "benefits.roi.risk.value": "-90%",
    "benefits.roi.risk.desc": "Counterfeiting Risks",

    "benefits.cta.title": "Calculate ROI for your company",
    "benefits.cta.button": "Talk to a Consultant",

    // Use Cases Page
    "usecases.hero.title": "Use Cases",
    "usecases.hero.subtitle": "Vertical solutions designed for the specific challenges of the most demanding industrial sectors.",
    "usecases.auto.badge": "Automotive",
    "usecases.auto.title": "Transparent Supply Chain",
    "usecases.auto.desc": "In automotive, compliance with IATF 16949 standards is critical. TRUSTUP ensures every component, from the smallest bolt to the full chassis, has a certified history.",
    "usecases.auto.items": [
      "Complete traceability of safety components",
      "Automated management of supplier certificates",
      "Digital Battery Passport",
      "Recall cost reduction thanks to precise data"
    ],
    "usecases.medical.badge": "Medical",
    "usecases.medical.title": "Regulatory Compliance and Device Traceability",
    "usecases.medical.desc": "In the medical sector, traceability and regulatory compliance are critical. TRUSTUP creates a complete digital dossier for every medical device, ensuring compliance with MDR, ISO 13485, and traceability throughout the entire supply chain.",
    "usecases.medical.items": [
      "Complete traceability of the medical device along the supply chain",
      "Automated management of MDR and ISO 13485 compliance",
      "Technical documentation and certifications always available",
      "Complete audit trail for regulatory inspections"
    ],
    "usecases.electronics.badge": "Electronics",
    "usecases.electronics.title": "Critical Component Traceability",
    "usecases.electronics.desc": "In the electronics sector, supply chain management is complex and global. TRUSTUP ensures complete traceability of every critical component, from semiconductors to integrated circuits, ensuring regulatory compliance and product authenticity.",
    "usecases.electronics.items": [
      "Complete traceability of critical components and semiconductors",
      "Automatic certification of origin and authenticity",
      "Management of RoHS and REACH compliance",
      "Prevention of counterfeit and refurbished components"
    ],
    "usecases.cosmetics.badge": "Cosmetics",
    "usecases.cosmetics.title": "Brand Transparency and Authenticity",
    "usecases.cosmetics.desc": "In the cosmetics sector, consumer trust is everything. TRUSTUP guarantees the natural origin of ingredients and protects the brand from counterfeiting.",
    "usecases.cosmetics.items": [
      "Traceability of organic and natural supply chains",
      "Anti-counterfeiting protection with NFC/QR",
      "Verifiable Vegan and Cruelty-Free certification",
      "Direct consumer engagement"
    ],
    "usecases.machinery.badge": "OEM & Plants",
    "usecases.machinery.title": "Equipment-as-a-Service",
    "usecases.machinery.desc": "Transform machine sales into recurring service revenue. TRUSTUP certifies actual usage, maintenance, and the authenticity of installed spare parts, enabling secure Pay-per-Use models.",
    "usecases.machinery.items": [
      "Certified Pay-per-Use business models",
      "Intellectual Property (IP) protection",
      "Traceability of original spare parts",
      "Shared digital plant logbook"
    ],
    "usecases.manu.badge": "Manufacturing",
    "usecases.manu.title": "Smart Factory & Equipment",
    "usecases.manu.desc": "For industrial machinery manufacturers, Digital Twin is key to enabling new business models like Equipment-as-a-Service.",
    "usecases.manu.items": [
      "Digital log of maintenance and repairs",
      "Automatic certification of testing",
      "Rapid access to technical documentation in the field",
      "Intellectual property protection of CAD drawings"
    ],
    "usecases.certs.badge": "Certifications",
    "usecases.certs.title": "Quality Management & Audit",
    "usecases.certs.desc": "Drastically simplifies the ISO audit and certification process. No more hunting for paper documents before inspection.",
    "usecases.certs.corporate.title": "Corporate Certifications",
    "usecases.certs.corporate.items": [
      "ISO 9001 (Quality)",
      "ISO 14001 (Environment)",
      "ISO 45001 (Safety)",
      "Social Responsibility"
    ],
    "usecases.certs.process.title": "Process Certifications",
    "usecases.certs.process.items": [
      "Production Audits",
      "In-line Quality Control",
      "Predictive Maintenance",
      "Energy Efficiency"
    ],
    "usecases.certs.supplier.title": "Supplier Certifications",
    "usecases.certs.supplier.items": [
      "Supplier Qualification",
      "Raw Material Traceability",
      "Ethical Compliance",
      "Supply Chain Audit"
    ],
    "usecases.certs.material.title": "Material Certifications",
    "usecases.certs.material.items": [
      "Technical Datasheets",
      "Lab Tests",
      "Controlled Origin",
      "Material Sustainability"
    ],
    "usecases.cta.title": "Have a specific use case?",
    "usecases.cta.button": "Contact Us",

    // Technology Overview Page
    "tech.overview.hero.title": "Trustless Technology",
    "tech.overview.hero.subtitle": "Decentralized architecture, open standards, and advanced cryptography to ensure data integrity without intermediaries.",
    "tech.overview.stack.did.title": "Decentralized Identity (DID)",
    "tech.overview.stack.did.desc": "Every asset receives a sovereign identity based on W3C standards. This ID is independent of any centralized registry and remains under the asset owner's control.",
    "tech.overview.stack.vc.title": "Verifiable Credentials (VC)",
    "tech.overview.stack.vc.desc": "Data are not simple database records, but cryptographically signed attestations. Anyone can verify authenticity and integrity without contacting the issuer.",
    "tech.overview.stack.sc.title": "Smart Contracts",
    "tech.overview.stack.sc.desc": "Business logic executed automatically on blockchain. Manages access rules, ownership transfers, and event validation transparently and immutably.",
    "tech.overview.arch.title": "Hybrid Architecture",
    "tech.overview.arch.desc": "We combine the speed and scalability of traditional databases for non-critical data with blockchain security for verification data.",
    "tech.overview.arch.offchain.title": "Off-Chain Storage",
    "tech.overview.arch.offchain.desc": "Voluminous data (images, CAD, documents) saved on distributed storage (IPFS) or secure cloud, referenced via hash.",
    "tech.overview.arch.onchain.title": "On-Chain Verification",
    "tech.overview.arch.onchain.desc": "Only \"digital fingerprints\" (hashes) and cryptographic proofs are saved on blockchain, ensuring privacy and performance.",
    "tech.overview.cta.title": "Deep dive into technology",
    "tech.overview.cta.button": "Technical Documentation",

    // Technology Page (Detailed)
    "tech.hero.title": "Trustless Technology",
    "tech.hero.subtitle": "Decentralized architecture, open standards, and advanced cryptography.",
    "tech.did.title": "Decentralized Identity (DID)",
    "tech.did.desc": "Global unique identifiers independent of central authorities.",
    "tech.vc.title": "Verifiable Credentials (VC)",
    "tech.vc.desc": "Cryptographically signed digital attestations, instantly verifiable.",
    "tech.sc.title": "Smart Contracts",
    "tech.sc.desc": "Business logic executed automatically on blockchain.",
    "tech.interop.title": "Interoperability & Compliance",
    "tech.interop.desc": "Designed to integrate with existing systems and comply with regulations.",
    "tech.interop.api.title": "REST & GraphQL APIs",
    "tech.interop.api.desc": "Easy integration with ERP, MES, and legacy systems.",
    "tech.interop.gaiax.title": "GAIA-X Ready",
    "tech.interop.gaiax.desc": "Compliant with European standards for data sovereignty.",
    "tech.interop.gdpr.title": "GDPR Compliant",
    "tech.interop.gdpr.desc": "Privacy by design and granular consent management.",

    // Open Source Page
    "opensource.hero.badge": "Open Standards",
    "opensource.hero.title": "Open Source & Standards",
    "opensource.hero.subtitle": "We believe trust must be built on open foundations. That's why we adopt and contribute to major global standards.",
    "opensource.global.title": "Global Standards",
    "opensource.global.intro": "We adopt internationally recognized protocols to ensure your asset data is universally readable, interoperable, and secure, regardless of the platform used.",
    "opensource.eu.title": "European Standards",
    "opensource.eu.intro": "We align with European Union directives for data sovereignty and digital identity, ensuring your company is ready for current and future regulations.",

    "opensource.standards.w3c.title": "Sovereign Identity",
    "opensource.standards.w3c.desc": "We use decentralized identifiers (DID) and verifiable credentials (VC) to give assets an autonomous, secure, and portable digital identity, eliminating dependence on proprietary centralized registries.",
    "opensource.standards.unece.title": "Trade Digitalization",
    "opensource.standards.unece.desc": "We implement standard data models for international supply chains, facilitating the exchange of verifiable digital trade and logistics documents between global partners.",
    "opensource.standards.gs1.title": "Global Traceability",
    "opensource.standards.gs1.desc": "We integrate the GS1 Digital Link standard to connect physical products to their digital twin, allowing universal scanning (e.g., QR Code) that works anywhere in the world.",
    "opensource.standards.gleif.title": "Certified Legal Identity",
    "opensource.standards.gleif.desc": "We link asset identity to company legal identity (LEI), creating a verifiable chain of trust certifying who owns or produced a good.",
    "opensource.standards.iso.title": "Quality and Security",
    "opensource.standards.iso.desc": "Our data structures comply with ISO standards for quality management and information security, ensuring digital processes are robust and aligned with industrial best practices.",

    "opensource.standards.gaiax.title": "Data Sovereignty",
    "opensource.standards.gaiax.desc": "We adhere to GAIA-X principles to create open and transparent data ecosystems, where companies maintain full control over where their data resides and who can access it.",
    "opensource.standards.nis2.title": "Cybersecurity Compliance",
    "opensource.standards.nis2.desc": "The platform is designed according to NIS2 directive requirements, offering advanced cybersecurity levels to protect critical infrastructure and sensitive industrial data.",
    "opensource.standards.eidas.title": "EU Digital Trust",
    "opensource.standards.eidas.desc": "We support the eIDAS 2.0 framework and EU Digital Identity Wallet, allowing the use of legally recognized digital identities across Europe to sign and validate transactions.",
    "opensource.standards.eidas2.title": "eIDAS 2.0",
    "opensource.standards.eidas2.desc": "Full compatibility with the new European digital identity regulation.",
    "opensource.european.intro": "We align with European Union directives for data sovereignty and digital identity.",

    // About Page
    "about.hero.title": "Building Digital Trust",
    "about.hero.subtitle": "Our mission is to make every physical asset verifiable, secure, and transparent through technology.",
    "about.mission.title": "Our Mission",
    "about.mission.desc": "Enabling an industrial economy where trust is native to the data, not the intermediary.",
    "about.vision.title": "Our Vision",
    "about.vision.desc": "A world where every product tells its true story, verifiable by anyone, anywhere.",
    "about.team.title": "The Team",
    "about.team.desc": "Blockchain experts, industrial engineers, and digital visionaries united to transform the industry.",

    "about.values.title": "Our Values",
    "about.values.subtitle": "Fundamental principles guiding every decision and line of code we write.",
    "about.values.security": "Security First",
    "about.values.security.desc": "We do not compromise on data protection. Advanced encryption and military standards are our baseline.",
    "about.values.collab": "Open Collaboration",
    "about.values.collab.desc": "We believe in open source and shared standards. True innovation comes from cooperation, not silos.",
    "about.values.innovation": "Pragmatic Innovation",
    "about.values.innovation.desc": "We don't follow hype. We implement frontier technologies only when they bring tangible and measurable value.",
    "about.cta.title": "Join the Industrial Revolution",
    "about.cta.button": "Work with Us",

    // Contact Page
    "contact.hero.title": "Talk to Us",
    "contact.hero.subtitle": "We are here to answer your questions and guide you through digital transformation.",
    "contact.info.email": "Email",
    "contact.form.firstName": "First Name",
    "contact.form.lastName": "Last Name",
    "contact.form.company": "Company",
    "contact.form.email": "Company Email",
    "contact.form.sector": "Sector",
    "contact.form.sector.placeholder": "Select a sector",
    "contact.form.sector.auto": "Automotive",
    "contact.form.sector.manu": "Manufacturing",
    "contact.form.sector.aero": "Aerospace",
    "contact.form.sector.other": "Other",
    "contact.form.message": "Message",
    "contact.form.message.placeholder": "How can we help you?",
    "contact.form.privacy": "I have read and accept the Privacy Policy",
    "contact.form.submit": "Send Message",
    "contact.form.submitting": "Sending...",
    "contact.form.success": "Message sent successfully! We will get back to you shortly.",

    // Configurator Page
    "configurator.back": "Back to Dashboard",
    "configurator.logout": "Logout",
    "configurator.title": "TRUSTUP Pricing Configurator",
    "configurator.subtitle": "Configure services, estimate volumes and get a personalized quote",
    "configurator.mandatory": "MANDATORY",
    "configurator.oneTime": "one-time",
    "configurator.perQuarter": "/ quarter",
    "configurator.includes": "Includes:",

    // Services
    "configurator.services.saas.name": "Platform SaaS Subscription",
    "configurator.services.saas.desc": "Access to TRUSTUP platform with all base features (always included)",
    "configurator.services.saas.inc1": "Web platform access",
    "configurator.services.saas.inc2": "Digital certificate management",
    "configurator.services.saas.inc3": "100GB storage",
    "configurator.services.saas.inc4": "Basic technical support",
    "configurator.services.saas.inc5": "Platform updates",

    "configurator.services.startup.name": "TRUSTUP Activation",
    "configurator.services.startup.desc": "Complete tenant setup, configuration, onboarding and operational training",
    "configurator.services.startup.inc1": "Tenant and roles setup",
    "configurator.services.startup.inc2": "Asset digital identity modeling",
    "configurator.services.startup.inc3": "Certificate taxonomy definition",
    "configurator.services.startup.inc4": "Smart Contract setup",
    "configurator.services.startup.inc5": "Initial data import",
    "configurator.services.startup.inc6": "Staff training",

    "configurator.services.vlei.name": "vLEI Legal Identity",
    "configurator.services.vlei.desc": "vLEI (verifiable Legal Entity Identifier) integration for blockchain legal identity",
    "configurator.services.vlei.inc1": "Corporate DID creation",
    "configurator.services.vlei.inc2": "vLEI association",
    "configurator.services.vlei.inc3": "Blockchain notarization",
    "configurator.services.vlei.inc4": "Public verification setup",

    "configurator.services.api.name": "Entity API Integration",
    "configurator.services.api.desc": "Connection with external registries and entities for automatic verifications (includes quarterly fee €450)",
    "configurator.services.api.inc1": "Custom connector setup",
    "configurator.services.api.inc2": "External registry integration",
    "configurator.services.api.inc3": "Automatic verifications",
    "configurator.services.api.inc4": "Data synchronization",
    "configurator.services.api.inc5": "+ API Add-on Fee: €450/quarter",

    // Service Selector
    "configurator.selector.title": "Select Services",
    "configurator.selector.base": "Base Services",
    "configurator.selector.addons": "Additional Modules (Optional)",

    // Volume Estimator
    "configurator.volumes.title": "Estimate Annual Volumes",
    "configurator.volumes.totalCredits": "Total Estimated Credits",
    "configurator.volumes.suggested": "Suggested Package: {name}",
    "configurator.volumes.suggestedDesc": "{credits} credits at €{price} (€{pricePerCredit}/credit)",
    "configurator.volumes.remaining": "+{remaining} remaining",
    "configurator.volumes.howItWorks": "How it works:",
    "configurator.volumes.howItWorksDesc": "Each operation consumes 1 credit. Credits never expire and accumulate in your account. You can purchase additional packages at any time.",

    "configurator.volumes.certificates": "Single Certificates",
    "configurator.volumes.certificates.desc": "Number of individual certificates to notarize annually",
    "configurator.volumes.dossiers": "Complete Dossiers",
    "configurator.volumes.dossiers.desc": "Number of dossiers (certificate collections) to notarize",
    "configurator.volumes.updates": "Updates",
    "configurator.volumes.updates.desc": "Number of updates/new versions of existing certificates",
    "configurator.volumes.revokes": "Revocations",
    "configurator.volumes.revokes.desc": "Number of expected certificate revocations",
    "configurator.volumes.milestones": "Event Milestones",
    "configurator.volumes.milestones.desc": "Number of events/milestones to track (optional)",
    "configurator.volumes.did": "Product DID Registrations",
    "configurator.volumes.did.desc": "Number of product digital identities to register",

    // Credit Pack Selector
    "configurator.credits.title": "Select Credit Package",
    "configurator.credits.estimated": "Estimated Credits Needed",
    "configurator.credits.suggested": "Recommended",
    "configurator.credits.credits": "credits",
    "configurator.credits.perCredit": "/credit",
    "configurator.credits.savings": "Save {savings}%",
    "configurator.credits.insufficient": "Insufficient credits for estimated volumes",
    "configurator.credits.remaining": "+{remaining} remaining credits",
    "configurator.credits.note": "Credits never expire and accumulate in your account. You can purchase additional packages at any time. Each operation (certificate, dossier, update, revocation, etc.) consumes 1 credit.",

    // Pricing Summary
    "configurator.summary.title": "Quote Summary",
    "configurator.summary.subtitle": "Complete configuration for the first year of service",
    "configurator.summary.setup.title": "Setup Costs",
    "configurator.summary.setup.subtitle": "One-time initial investment",
    "configurator.summary.setup.startup": "TRUSTUP Activation",
    "configurator.summary.setup.vlei": "vLEI Legal Identity",
    "configurator.summary.setup.api": "Entity API Integration",
    "configurator.summary.setup.total": "Total Setup",

    "configurator.summary.recurring.title": "Recurring Fees",
    "configurator.summary.recurring.subtitle": "Annual operating costs",
    "configurator.summary.recurring.base": "Base SaaS Subscription (€{monthly}/month)",
    "configurator.summary.recurring.vlei": "vLEI Add-on (€{monthly}/month)",
    "configurator.summary.recurring.api": "API Add-on (€{monthly}/month)",
    "configurator.summary.recurring.year1": "Total Year 1",
    "configurator.summary.recurring.year2": "Year 2 Projection (M2 +{rate}%)",
    "configurator.summary.recurring.satoshi": "Satoshi Equivalent (fixed)",

    "configurator.summary.credits.title": "Blockchain Credits",
    "configurator.summary.credits.subtitle": "On-chain operations package",
    "configurator.summary.credits.selected": "Selected Package",
    "configurator.summary.credits.estimated": "Estimated Credits Needed",
    "configurator.summary.credits.cost": "Credits Cost",

    // Short keys for PricingSummary
    "configurator.summary.setup": "Setup Costs",
    "configurator.summary.setupDesc": "One-time initial investment",
    "configurator.summary.recurring": "Recurring Fees",
    "configurator.summary.recurringDesc": "Annual operating costs",
    "configurator.summary.year1": "Total Year 1",
    "configurator.summary.year2Projection": "Year 2 Projection (M2 +{rate}%)",
    "configurator.summary.satoshiFixed": "Satoshi Equivalent (fixed)",
    "configurator.summary.credits": "Blockchain Credits",
    "configurator.summary.creditsDesc": "On-chain operations package",
    "configurator.summary.selectedPack": "Selected Package",
    "configurator.summary.estimatedCredits": "Estimated Credits Needed",
    "configurator.summary.creditsCost": "Credits Cost",
    "configurator.summary.totalInvestment": "Total Investment",
    "configurator.summary.firstYearComplete": "Complete First Year",
    "configurator.summary.initialSetup": "Initial Setup",
    "configurator.summary.year1Fees": "Year 1 Fees",
    "configurator.summary.blockchainCredits": "Blockchain Credits",
    "configurator.summary.vleiActions": "vLEI Actions",
    "configurator.summary.vleiActionsDesc": "Costs for vLEI legal identity updates",
    "configurator.summary.vleiUpdatesPerYear": "Updates/Year",
    "configurator.summary.vleiPricePerAction": "Price per Action",
    "configurator.summary.vleiActionsCost": "vLEI Actions Cost",
    "configurator.summary.selectedCurrency": "Selected Currency:",
    "configurator.summary.eurDesc": "Fees revalued annually (M2 +{rate}%)",
    "configurator.summary.btcDesc": "Fixed fees in satoshi ({sats} sats/year)",
    "configurator.summary.downloadPDF": "Download PDF",
    "configurator.summary.saveConfig": "Save Configuration",
    "configurator.summary.requestContact": "Request Contact",

    "configurator.summary.total.title": "Total Investment",
    "configurator.summary.total.year1": "Complete First Year",
    "configurator.summary.total.setup": "Initial Setup",
    "configurator.summary.total.recurring": "Year 1 Fees",
    "configurator.summary.total.credits": "Blockchain Credits",
    "configurator.summary.total.vleiActions": "vLEI Actions",
    "configurator.summary.total.currency": "Selected Currency:",
    "configurator.summary.total.eurDesc": "Fees revalued annually (M2 +{rate}%)",
    "configurator.summary.total.btcDesc": "Fixed fees in satoshi ({sats} sats/year)",

    "configurator.summary.download": "Download PDF",
    "configurator.summary.save": "Save Configuration",
    "configurator.summary.contact": "Request Contact"
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('it');

  const t = (key: string) => {
    const value = translations[language];

    // 1. Try exact match first (most common case for flat keys)
    if (value[key as keyof typeof value]) {
      return value[key as keyof typeof value];
    }

    // 2. Try nested lookup (for arrays/objects like usecases.certs.items)
    const keys = key.split('.');
    let current: any = value;

    for (const k of keys) {
      if (current === undefined || current === null) return key;
      current = current[k];
    }

    return current !== undefined ? current : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
